{% extends '../layouts/application.swig' %}

{% block content %}
  <h1>Fashion Deals App (ember)</h1>

  <script type="text/x-handlebars" data-template-name="deals">
    <section id="fashiondealsapp">

    </section>
  </script>

  <script src="js/lib/ember/ember.js"></script>
  <script src="js/lib/ember/ember-data.js"></script>
  <script src="js/ember/application.js"></script>
  <script src="js/ember/routes.js"></script>
  <script src="js/ember/models/deal.js"></script>
{% endblock %}
